application: neumont-dlc-2014-october-23
version: 2-0-0

runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: creative-app-engine.html
    upload: creative-app-engine.html
  - url: /reveal.js
    static_dir: reveal.js
